export const GRUPO_PADRE = {
  BASICO_TEC_TECNICAS_E_INTEG: "Basico-Tec,Tecnicas e Integ.",
  MATERIAS_BASICAS: "Materias Basicas",
  MATERIAS_COMPLEMENTARIAS: "Materias Complementarias",
  MATERIAS_OPCIONALES: "Materias Opcionales",
} as const;
export type GrupoPadre = (typeof GRUPO_PADRE)[keyof typeof GRUPO_PADRE];

export const GRUPO_HIJO = {
  MATEMATICA: "MATEMATICA",
  CIENCIAS_EXPERIMENTALES: "CIENCIAS EXPERIMENTALES",
  GESTION_EN_ORGANIZACIONES: "GESTION EN ORGANIZACIONES",
  ARQUIT_S_OP_Y_REDES_DE_COMP: "ARQUIT, S.OP. Y REDES DE COMP.",
  PROGRAMACION: "PROGRAMACION",
  B_DATOS_Y_SIST_DE_INFORMACION: "B.DATOS Y SIST. DE INFORMACION",
  A_INTEG_TALLERES_PASANT_Y_PROY: "A.INTEG,TALLERES,PASANT.Y PROY",
  INVESTIGACION_OPERATIVA: "INVESTIGACION OPERATIVA",
  INT_ARTIFICIAL_Y_ROBOTICA: "INT.ARTIFICIAL Y ROBOTICA",
  CALCULO_NUMERICO_Y_SIMBOLICO: "CALCULO NUMERICO Y SIMBOLICO",
  INGENIERIA_DE_SOFTWARE: "INGENIERIA DE SOFTWARE",
  CIENCIAS_HUMANAS_Y_SOCIALES: "CIENCIAS HUMANAS Y SOCIALES",
  MATERIAS_OPCIONALES: "",
} as const;
export type GrupoHijo = (typeof GRUPO_HIJO)[keyof typeof GRUPO_HIJO];
