services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    env_file:
      - .env.prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    restart: unless-stopped

  processor-scraper:
    build:
      context: ./processor-scraper
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    restart: unless-stopped
