services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - processor-scraper

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  processor-scraper:
    build: ./processor-scraper
