services:
  backend:
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    ports:
      - '5173:5173'
    restart: unless-stopped

  processor-scraper:
    working_dir: /app
    volumes:
      - ./processor-scraper:/app
    ports:
      - '8000:8000'
    restart: unless-stopped
