services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app
    env_file:
      - ./backend/.env
    depends_on:
      - processor-scraper
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped

  processor-scraper:
    build: ./processor-scraper
    ports:
      - '8000:8000'
    volumes:
      - ./processor-scraper:/app
    working_dir: /app
    restart: unless-stopped
