services:
  core:
    build: ./core
    ports:
      - "3000:3000"
    volumes:
      - ./core:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app
    env_file:
      - ./core/.env
    depends_on:
      - pdf-processor
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    working_dir: /app
    env_file:
      - ./frontend/.env
    depends_on:
      - core
    restart: unless-stopped
  
  pdf-processor:
    build: ./pdf-processor
    ports:
      - "8000:8000"
    volumes:
      - ./pdf-processor:/app
    working_dir: /app
    restart: unless-stopped
