export const AREA = {
  BASICO_TEC_TECNICAS_E_INTEG: "Basico-Tec,Tecnicas e Integ.",
  MATERIAS_BASICAS: "Materias Basicas",
  MATERIAS_COMPLEMENTARIAS: "Materias Complementarias",
  MATERIAS_OPCIONALES: "Materias Opcionales",
} as const;
export const AREA_VALUES = Object.values(AREA);

export const GRUPO = {
  MATEMATICA: "MATEMATICA",
  CIENCIAS_EXPERIMENTALES: "CIENCIAS EXPERIMENTALES",
  PROGRAMACION: "PROGRAMACION",
  ARQUIT_S_OP_Y_REDES_DE_COMP: "ARQUIT, S.OP. Y REDES DE COMP.",
  INT_ARTIFICIAL_Y_ROBOTICA: "INT.ARTIFICIAL Y ROBOTICA",
  B_DATOS_Y_SIST_DE_INFORMACION: "B.DATOS Y SIST. DE INFORMACION",
  CALCULO_NUMERICO_Y_SIMBOLICO: "CALCULO NUMERICO Y SIMBOLICO",
  INVESTIGACION_OPERATIVA: "INVESTIGACION OPERATIVA",
  INGENIERIA_DE_SOFTWARE: "INGENIERIA DE SOFTWARE",
  A_INTEG_TALLERES_PASANT_Y_PROY: "A.INTEG,TALLERES,PASANT.Y PROY",
  GESTION_EN_ORGANIZACIONES: "GESTION EN ORGANIZACIONES",
  CIENCIAS_HUMANAS_Y_SOCIALES: "CIENCIAS HUMANAS Y SOCIALES",
  MATERIAS_OPCIONALES: "MATERIAS OPCIONALES",
} as const;
export const GRUPO_VALUES = Object.values(GRUPO);

export const TIPO_APROBACION = {
  EXAMEN: "Examen",
  CURSO: "Curso",
} as const;

export const TIPO_INSTANCIA = {
  CURSO: "C",
  EXAMEN: "E",
} as const;

export const TIPO_REGLA = {
  AND: "AND",
  OR: "OR",
  NOT: "NOT",
  SOME: "SOME",
  UC: "UC",
  CREDITOS_GRUPO: "CREDITOS_GRUPO",
  CREDITOS_PLAN: "CREDITOS_PLAN",
} as const;

export const SEMESTRE_DE_DICTADO = {
  PRIMER_SEMESTRE: "1",
  SEGUNDO_SEMESTRE: "2",
} as const;

export const REQUISITOS_TITULO = {
  CREDITOS_TOTALES: 450,
  [GRUPO.MATEMATICA]: 70,
  [GRUPO.CIENCIAS_EXPERIMENTALES]: 10,
  [GRUPO.PROGRAMACION]: 60,
  [GRUPO.ARQUIT_S_OP_Y_REDES_DE_COMP]: 30,
  [GRUPO.INT_ARTIFICIAL_Y_ROBOTICA]: 0,
  [GRUPO.B_DATOS_Y_SIST_DE_INFORMACION]: 10,
  [GRUPO.CALCULO_NUMERICO_Y_SIMBOLICO]: 8,
  [GRUPO.INVESTIGACION_OPERATIVA]: 10,
  [GRUPO.INGENIERIA_DE_SOFTWARE]: 10,
  [GRUPO.A_INTEG_TALLERES_PASANT_Y_PROY]: 45,
  [GRUPO.GESTION_EN_ORGANIZACIONES]: 10,
  [GRUPO.CIENCIAS_HUMANAS_Y_SOCIALES]: 10,
  [GRUPO.MATERIAS_OPCIONALES]: 0,
};
