# Areas de formacion. TODO: Debemos tener un diccionario asi para cada carrera.
INGENIERIA_COMPUTACION_FORMATION_AREAS = {
    "Materias Basicas": ["MATEMATICA", "CIENCIAS EXPERIMENTALES"],
    "Basico-Tec,Tecnicas e Integ.": [
        "PROGRAMACION",
        "ARQUIT, S.OP. Y REDES DE COMP.",
        "INT.ARTIFICIAL Y ROBOTICA",
        "B.DATOS Y SIST. DE INFORMACION",
        "CALCULO NUMERICO Y SIMBOLICO",
        "INVESTIGACION OPERATIVA",
        "INGENIERIA DE SOFTWARE",
        "A.INTEG,TALLERES,PASANT.Y PROY",
        "GESTION EN ORGANIZACIONES",
    ],
    "Materias Complementarias": ["CIENCIAS HUMANAS Y SOCIALES"],
    "Materias Opcionales": ["MATERIAS OPCIONALES"],
}

# Lineas a omitir en el procesado del PDF. Corresponden a lineas de texto de la cabecera y pie de pagina de las paginas.
LINES_TO_SKIP = [
    "Código",
    "Verificar",
    "Página",
    "Escala de Notas",
    "Cambio de Plan",
    "Plan",
    "En cursoEstado Ingreso",
    "INGENIERIA EN COMPUTACION",
    "FACULTAD DE INGENIERÍA",
    "CERTIFICADO DE ESCOLARIDAD",
    "Estado:",
    " FechaUnidad",
    "Cred",
    "NotaEn",
    "Cant.",
    "Resultados Finales e Intermedios",
    "Normal Tipo de Inscripción: En curso Estado:",
    "Aprobación",
    "Unidad Curricular",
    "Nota  FechaCant.",
    "sin",
    "validezCant.",
    "Reproba",
    "ciones",
    "-cionesCred Actividad",
    "Curso",
    "*",
    "REFERENCIAS",
    "Conceptos Sin Concepto",
    "EMISIÓN",
    "1997Plan",
    " FACULTAD DE INGENIERÍA",
    "RESUMEN DE AVANCE:",
    "-cionesUnidad",
    "Concepto",
]